### ISSUE TITLE
WARNING during check

### ISSUE THREAD

**Issue by vegahi** [beanumber/citibike#11]
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'etl_extract.etl_citibike' ‘schema’
Functions with \usage entries need to have the appropriate \alias entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.

**Comment by beanumber** [comment]
Have you updated your version of `etl` recently? Are you using the `@inheritParams` directive for `etl_load()`?

**Comment by vegahi** [comment]
yes. I just downloaded the latest version of etl but I couldn't get rid of the warning message. All three functions take inherit parameters from  etl_extract `@inheritParams etl::etl_extract`. The extract function also take the year and month parameters.
