### ISSUE TITLE
How to deal with time without seconds?

### ISSUE THREAD

**Issue by vegahi** [beanumber/citibike#18]
I just found that part of reason that led to the failure of 201501 was the format difference. The pattern recognition I used was `ymd HMS`. For some reason, the date format is different and the second unit is missing. How should I handle with this problem?
@beanumber 

````
tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
1346,1/1/2015 0:01,1/1/2015 0:24,455,1 Ave & E 44 St,40.75001986,-73.96905301,265,Stanton St & Chrystie St,40.72229346,-73.99147535,18660,Subscriber,1960,2
363,1/1/2015 0:02,1/1/2015 0:08,434,9 Ave & W 18 St,40.74317449,-74.00366443,482,W 15 St & 7 Ave,40.73935542,-73.99931783,16085,Subscriber,1963,1

````

**Comment by beanumber** [comment]
Looks like you want `mdY HM`. What happened to the seconds? Is this what the raw data looks like?

**Comment by vegahi** [comment]
Yep. The raw data doesn't have that part. I am manually checking all files and see if others also have this problem.

**Comment by beanumber** [comment]
OK, sounds like you will just have to have another format to check in your `if` statement.

**Comment by vegahi** [comment]
For the records before 2017, there are three months that don't have the second units : 201501, 201502 and 201503.

**Comment by vegahi** [comment]
Even though there's no second units in the `csv` files, MySQL will automatically create 00 when reading in the data. Is it ok to leave it there? Or might it be a better idea to add statements and modify the columns in  `init.mysql` ?

**Comment by beanumber** [comment]
It's OK to leave it. You might want to add a note in the documentation that for certain months, the seconds don't seem to be recorded. 

Is it worth emailing the data provider about this?
