### ISSUE TITLE
Data merging problem 

### ISSUE THREAD

**Issue by vegahi** [beanumber/citibike#4]
Given the fact that the data files are relatively small, I decided to use the transform function to unzip all the files in the raw folder and put them in the load folder. (I think that the extract function is fine for now.) The next step is to combine all the monthly files together into a big csv file. I couldn't figure out a smart way to do that, so I posted the question on stackoverflow for help: http://stackoverflow.com/q/37444120/6311820. 
The other problem was that I came across the similar problem when running the transform function, could you help me with that? Thanks. @beanumber 

```
> bikes %>%
+   etl_transform()
No available methods. Did you write the method etl_transform.etl_citibike()?
```

**Comment by beanumber** [comment]
I replied to your post. As we discussed, I'm not sure that concatenating the files is the way to go here.

**Comment by beanumber** [comment]
I think we won't do this.
