### ISSUE TITLE
modify etl_transform to read the data into R, fix data types, and write to CSV

### ISSUE THREAD

**Issue by beanumber** [beanumber/citibike#7]
- read directly from ZIP files using `readr::read_csv` -- don't have to `unzip`
- use `lubridate` (if necessary) to make sure date and time columns have the right data type
- fix #1 
- write the CSVs in a uniform filename pattern

**Comment by liwencong1995** [comment]
I made some changes to `tel_transform` so that it only transforms the files specified. `years` and `months` variables were not used in the body of `etc_transform` before I made the changes.
