### ISSUE TITLE
What should etl_extract do when years and months are not valid?

### ISSUE THREAD

**Issue by liwencong1995** [beanumber/citibike#9]
For now, `etl_extract` downloads a file called `tripdata` when years and months are not valid. Should we use the `valid_year_month` function to create a table of valid years and months?

**Comment by beanumber** [comment]
Yes, I think so.

**Comment by liwencong1995** [comment]
I just checked etl_extract function again, and it filters out all valid zip files' names. However, it still downloads a file called `tripdata` when no valid date/file name is provided.

**Comment by beanumber** [comment]
Confirmed:

```
> etl_extract(bikes, months = 1:2)
trying URL 'https://s3.amazonaws.com/tripdata/'
downloaded 9565 bytes
```

@vegahi look at `etl::valid_year_months()` and see if it will help with this.
